// swiftlint:disable identifier_name
// swiftlint:disable sorted_enum_cases
enum WidgetLayoutIcon: String, CaseIterable, Codable {
    case faceSmiling = "face.smiling"
    case listBullet = "list.bullet"
    case bookmark = "bookmark"
    case mappin = "mappin"
    case booksVertical = "books.vertical"
    case gift = "gift"
    case graduationcap = "graduationcap"
    case document = "document"
    case creditcard = "creditcard"
    case forkKnife = "fork.knife"
    case pills = "pills"
    case stethoscope = "stethoscope"
    case house = "house"
    case building2 = "building.2"
    case buildingColumns = "building.columns"
    case tv = "tv"
    case headphones = "headphones"
    case leaf = "leaf"
    case pawprint = "pawprint"
    case cart = "cart"
    case bag = "bag"
    case shippingbox = "shippingbox"
    case tram = "tram"
    case snowflake = "snowflake"
    case flame = "flame"
    case briefcase = "briefcase"
    case wrenchAndScrewdriver = "wrench.and.screwdriver"
    case scissors = "scissors"
    case curlybraces = "curlybraces"
    case lightbulb = "lightbulb"
    case bubble = "bubble"
    case asterisk = "asterisk"
    case square = "square"
    case circle = "circle"
    case triangle = "triangle"
    case diamond = "diamond"
    case heart = "heart"
    case star = "star"
    case person3 = "person.3"
    case guitars = "guitars"
    case paintpalette = "paintpalette"
    case sunrise = "sunrise"
    case sunset = "sunset"
    case globeEuropeAfrica = "globe.europe.africa"
    case pencil = "pencil"
    case bicycle = "bicycle"

    var systemImage: String {
        rawValue
    }
}
